// <auto-generated />
using Market.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Market.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240107183904_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Market.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Computers"
                        });
                });

            modelBuilder.Entity("Market.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,3)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Description1",
                            Price = 1100m,
                            Title = "Product1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Description2",
                            Price = 1140m,
                            Title = "Product2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Description3",
                            Price = 1200m,
                            Title = "Product3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Description4",
                            Price = 11500m,
                            Title = "Product4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Description5",
                            Price = 1100m,
                            Title = "Product5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Description6",
                            Price = 1100m,
                            Title = "Product6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Description7",
                            Price = 11004m,
                            Title = "Product7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Description8",
                            Price = 1100m,
                            Title = "Product8"
                        });
                });

            modelBuilder.Entity("Market.Models.Entities.Product", b =>
                {
                    b.HasOne("Market.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
